### ISSUE TITLE
Comments on draft-teas-ns-packet-06

### ISSUE THREAD

**Issue by jie-dong** [tsaad-dev/drafts#33]
1.	The term “Slice-Flow Aggregate Topology” is used in the title of section 3.4. As discussed  it is not accurate and should be replaced by Network Resource Partition Topology. 

2.	The term “Slice Flow Aggregate Selector” is confusing. I understand you want it to cover both the global identifier and the per-node/per-link identifiers (e.g. use different resource aware SIDs for different NRPs). But in both cases, the identifier is for the transit nodes to identify the set of network resources allocated to an NRP. The current term could make people confused that it is used by the ingress node to select a set of flows to be part of a slice flow aggregate, to my understanding this is not your intention. My suggestion is to change this term to something like “Resource Partition Identifier”, which can be either a network-wide global ID or a node/link-specific ID.

3.	The control plane only mode of NRP.   The draft needs to clarify that in the control plane only NRP mode, what is the required behavior on the network nodes. Do the nodes need to maintain per NRP state or not? And since the “Slice Flow Aggregate Selector” is not required in this mode, can the nodes perform NRP-PHB on received packets? Or is NRP-PHB only applicable to the data plane mode? Moreover, if multiple NRPs share the same group of network resources, how could the traffic mapped to different NRPs be differentiated in the forwarding plane? If the behavior of these NRPs are the same, why treat them as separate NRPs? 

4.	The NRP-PHB.  I agree with Med that this requires some generalization or extension of the PHB concept.  Then this draft needs to add NRP-PHB to the terminology section, and describes what is the difference between NRP-PHB and Diffserv PHB.

**Comment by tsaad-dev** [comment]
The term “Slice-Flow Aggregate Topology” is used in the title of section 3.4. As discussed it is not accurate and should be replaced by Network Resource Partition Topology.
[TS]: addressed. Issue closed.

The term “Slice Flow Aggregate Selector” is confusing. I understand you want it to cover both the global identifier and the per-node/per-link identifiers (e.g. use different resource aware SIDs for different NRPs). But in both cases, the identifier is for the transit nodes to identify the set of network resources allocated to an NRP. The current term could make people confused that it is used by the ingress node to select a set of flows to be part of a slice flow aggregate, to my understanding this is not your intention. My suggestion is to change this term to something like “Resource Partition Identifier”, which can be either a network-wide global ID or a node/link-specific ID.
[TS]: selector is more generic. The selector is carried in the packet/flow. The selector does not have to be an ID (e.g. it can be service label). The term "Slice Flow Aggregate Selector" can be generalized to "Flow Aggregate Selector". The YANG model will not have "slice" and will be generic.

The control plane only mode of NRP. The draft needs to clarify that in the control plane only NRP mode, what is the required behavior on the network nodes. Do the nodes need to maintain per NRP state or not? And since the “Slice Flow Aggregate Selector” is not required in this mode, can the nodes perform NRP-PHB on received packets? Or is NRP-PHB only applicable to the data plane mode? Moreover, if multiple NRPs share the same group of network resources, how could the traffic mapped to different NRPs be differentiated in the forwarding plane? If the behavior of these NRPs are the same, why treat them as separate NRPs?
[TS]: no Slice Flow Aggregate Selector is needed in control plane only mode. Also, no NRP-PHB is needed in control plane only mode. Optionally add before adoption.

The NRP-PHB. I agree with Med that this requires some generalization or extension of the PHB concept. Then this draft needs to add NRP-PHB to the terminology section, and describes what is the difference between NRP-PHB and Diffserv PHB.

[TS]:
NRP-ID:
Update terminology to indicate can be used in control or management plane to identify NRP resources.
